export const CATE_SUCCESS="CATE_SUCCESS";
export const CATE_REQUEST="CATE_REQUEST";
export const CATE_ERROR="CATE_ERROR";
export const CATE_RESET="CATE_RESET";

export const CATE_FIND_SUCCESS="CATE_FIND_SUCCESS";
export const CATE_FIND_REQUEST="CATE_FIND_REQUEST";
export const CATE_FIND_ERROR="CATE_FIND_ERROR";