export const SIGNIN_USER="SIGNIN_USER";
export const SIGNIN_USER_REQUEST="SIGNIN_USER_REQUEST";
export const SIGNIN_USER_ERROR="SIGNIN_USER_ERROR";
export const SIGNOUT_USER="SIGNOUT_USER";
export const SET_CURRENT_USER="SET_CURRENT_USER";
export const FETCH_USER_INFO="FETCH_USER_INFO";
